# Generated by Django 5.1.6 on 2025-03-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_n', models.IntegerField(default=0)),
                ('e_date', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
            ],
        ),
    ]
