# Generated by Django 5.1.6 on 2025-03-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycard', '0002_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_n',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='e_date',
            field=models.CharField(max_length=7),
        ),
    ]
