# Generated by Django 5.1.6 on 2025-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='allmoney',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
